Make the list of banned users configurable  Draft pull
fedora-infra/fedbadges pull request #137
Opened 2024-11-07 16:11 UTC by jeffiscow2

2024-11-08 15:00 UTC, abompard requested changes
Thanks, please also add the list to the `fedbadges.toml.example` file.

2024-11-08 15:00 UTC, abompard commented on devel/ansible/roles/dev/files/config.toml
> +skip_users = [
This list should be added before `[consumer_config.cache]` in the configuration file in order for it to end up in the main configuration directory, here it'll go in the `badge_issuer` subdirectory.

2024-11-08 15:00 UTC, abompard commented on fedbadges/rules.py
> +        candidates = candidates.difference(self.skip_users)
Here, `self.skip_users` is the filename `"config.toml"`. We want it to be the actual list of usernames.

You can get that list by using the `self.config.get("skip_users", [])`.

2024-11-08 15:00 UTC, abompard commented
Also, please squash your commits.

2024-11-11 12:10 UTC, jeffiscow2 commented
I Cant get the commits to squash and I've tried a million things. I pretty shure I made it worse... lol

2024-11-28 10:32 UTC, abompard commented
OK I think I fixed the squashes :-)

2024-11-28 10:46 UTC, abompard requested changes

2024-11-28 10:46 UTC, abompard commented on fedbadges/rules.py
> -
You don't really need to add this loop, you could reuse the previous "difference" line. You just need to convert the datastructure that comes from the configuration file as a list into a set:
```python
candidates = candidates.difference(frozenset(self.config.get("skip_users", [])))
```

2024-11-28 10:46 UTC, abompard commented on fedbadges.toml.example
> +    "root",
Looks like there are less entries in this list than in the one that was in the `rules.py` file initially.

2024-12-06 01:11 UTC, jeffiscow2 reviewed
I turned rules reload back to 15 from 1

2024-12-06 01:11 UTC, jeffiscow2 commented on fedbadges.toml.example
> +    "root",
ope added the rest of the skip_users

2024-12-09 08:11 UTC, abompard requested changes

2024-12-09 08:11 UTC, abompard commented on .vscode/settings.json
> +{
This file is unrelated to this PR, please don't add it.

2024-12-09 08:11 UTC, abompard commented on fedbadges.toml.example
> +# Users skped when awarding badges
Typo here.

2024-12-09 08:11 UTC, abompard commented on fedbadges/rules.py
> +
You don't really need to add this empty line, comments are usually right above what they are commenting.

2024-12-09 08:19 UTC, abompard commented
Looks like you've merged your local copy into the changed that I had made to this pull request, which added back all the commits including merge conflicts.
I'm going to push my changes again. Then you can do `git reset --hard origin/develop` and it'll bring your local copy in line with the PR. I'll incorporate the changes you did in ff8787f.

2024-12-09 08:30 UTC, abompard commented
The problem may be coming from the fact that the Git integration in VS Code is really basic and doesn't let you do advanced stuff without an additional plugin. In any case, please remember to check the "Files changed" section of a PR after you've pushed, to make sure the changes are exactly what you want in the PR and nothing else.

2024-12-09 09:17 UTC, merged